apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: keda-worker-scaler
  labels:
    deploymentName: keda-worker
spec:
  scaleTargetRef:
    deploymentName: keda-worker
  pollinginterval: 5
  cooldownperiod: 10
  minReplicaCount: 0
  maxReplicaCount: 16
  triggers:
  - type: azure-servicebus
    metadata:
      queueName: kedawork
      connection: sbConnectionString
